# instructions: you only need numpy for the following questions, no need to use pandas. 

In [2]:
# 1. Find the row, column and overall means for the following matrix:

# m = np.arange(12).reshape((3,4))
import numpy as np
a=np.mat(np.arange(12).reshape((3,4)))
a

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [3]:
a.mean(axis=0)

matrix([[ 4.,  5.,  6.,  7.]])

In [4]:
a.mean(axis=1)

matrix([[ 1.5],
        [ 5.5],
        [ 9.5]])

In [5]:
np.mean(a)

5.5

In [1]:
# 2. Create a 10 by 6 matrix of random uniform numbers. Set all rows with any entry less than 0.1 to be zero.
import numpy as np
a=np.random.uniform(size=60).reshape(10,6)
a[np.any(a<.1,axis=1)]=0
b=np.mat(a)
b

matrix([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ],
        [ 0.68731098,  0.46255716,  0.67888263,  0.56194737,  0.61664749,
          0.14860609],
        [ 0.25795482,  0.51095828,  0.24689155,  0.11747582,  0.80973925,
          0.55984854],
        [ 0.89179377,  0.69366818,  0.58610626,  0.96851222,  0.29588872,
          0.97612051],
        [ 0.70318405,  0.72858551,  0.69509749,  0.42383789,  0.14478219,
          0.99027574],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ],
        [ 0.14376146,  0.24235961,  0.26253559,  0.62287732,  0.79828315,
          0.73065787],
        [ 0.89946889,  0.92776705,  0.11342903,  0.17225967,  0.90327691,
          0.16496797],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ],
        [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ]])

In [8]:
# 3. Generate six random integer numbers between 10 and 20.

c=np.mat(np.random.randint(10,20,6))
c

matrix([[13, 14, 15, 17, 14, 18]])

In [25]:
# 4. Create an array of 8 random numbers and sort it. 

d=np.random.rand(8)
np.sort(d)

array([ 0.1503579 ,  0.2461864 ,  0.38088025,  0.41589685,  0.46324174,
        0.61014634,  0.76844917,  0.95402776])

In [16]:
# 5. Create a program to calculate pi - tip: make use of random number and calculation to do this. Do NOT use building functions 
# or libraries. need 3 decimal points accuracy. 

import math
p=np.random.uniform(0,100000)
pi=math.radians(p)*(math.sin(math.radians(180)/math.radians(p)))
round(pi,3)

3.142

In [121]:
import random
n=10000000
a=0
for i in range(n):
    x=random.random()
    y=random.random()
    if x**2 + y**2 <= 1.000:
        a+=1
pi=(a/n)*4
round(pi,3)

3.142

##  Just insert your answer and ouput into this notebook file and then print out a hardcopy, bring it to class next Monday. 
##  Enjoy your assignment 1. 