# instructions: you only need numpy for the following questions, no need to use pandas. 

In [1]:
# 1. Find the row, column and overall means for the following matrix:
import numpy as np
m = np.arange(12).reshape((3,4))

# answer 

m = np.arange(12).reshape((3,4))
print(m)
print ("OVerall", m.mean())
print ("Row", m.mean(1))
print ("Columne", m.mean(0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
OVerall 5.5
Row [ 1.5  5.5  9.5]
Columne [ 4.  5.  6.  7.]


In [2]:
# 2. Create a 10 by 6 matrix of random uniform numbers. Set all rows with any entry less than 0.1 to be zero.

# answer

xs= np.random.random((10,6))
print (xs)
xs[(xs < 0.1).any(axis=1), :] = 0
print (xs)


[[ 0.21720105  0.51675971  0.90888221  0.23018026  0.4687185   0.26359687]
 [ 0.03379953  0.61398597  0.76895385  0.11031804  0.88617518  0.2699013 ]
 [ 0.37993079  0.53920915  0.61772441  0.53023903  0.3050967   0.57257161]
 [ 0.59914669  0.25760562  0.64932417  0.26492232  0.65888631  0.07849046]
 [ 0.71398899  0.07559732  0.12621428  0.76748486  0.02167162  0.97779157]
 [ 0.45470256  0.79608937  0.01179232  0.75031065  0.59151595  0.48758594]
 [ 0.06065284  0.76404225  0.13141284  0.73573864  0.60998548  0.34705671]
 [ 0.42330583  0.16881465  0.64007765  0.21880995  0.80559531  0.29505957]
 [ 0.38906356  0.18462025  0.3418836   0.45806974  0.85902863  0.09928069]
 [ 0.19746893  0.77069249  0.0864474   0.41178439  0.45903042  0.79592313]]
[[ 0.21720105  0.51675971  0.90888221  0.23018026  0.4687185   0.26359687]
 [ 0.          0.          0.          0.          0.          0.        ]
 [ 0.37993079  0.53920915  0.61772441  0.53023903  0.3050967   0.57257161]
 [ 0.          0.       

In [3]:
# 3. Generate six random integer numbers between 10 and 20.

# answer 

x = np.random.randint(low=10, high=20, size=6)
print(x)

[15 19 18 15 13 17]


In [4]:
# 4. Create an array of 8 random numbers and sort it. 

# answer

import numpy as np
x = np.random.random(8)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)

Original array:
[ 0.03754453  0.87678822  0.92794915  0.10904789  0.48388853  0.88475643
  0.54832051  0.57991033]
Sorted array:
[ 0.03754453  0.10904789  0.48388853  0.54832051  0.57991033  0.87678822
  0.88475643  0.92794915]


In [5]:
# 5. Create a program to calculate pi - tip: make use of random number and calculation to do this. Do NOT use building functions 
# or libraries. need 3 decimal points accuracy. 


s=20000000
data=np.random.uniform(-1,1,s).reshape(10000000,2)
count=0

for i in data:
    if np.square(i[0])+np.square(i[1])<1:
        count+=1
pi=8*count/s

print(pi)

3.1415952


##  Just insert your answer and ouput into this notebook file and then print out a hardcopy, bring it to class next Monday. 
##  Enjoy your assignment 1. 