In [1]:
import numpy as np

In [2]:
a=np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [3]:
np.tril(a)

array([[ 0,  0,  0,  0],
       [ 4,  5,  0,  0],
       [ 8,  9, 10,  0],
       [12, 13, 14, 15]])

In [4]:
# what if you only want the lower triangle
np.tril(a,-1)

array([[ 0,  0,  0,  0],
       [ 4,  0,  0,  0],
       [ 8,  9,  0,  0],
       [12, 13, 14,  0]])

In [5]:
np.triu(a)

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 0,  0, 10, 11],
       [ 0,  0,  0, 15]])

In [6]:
np.diag(a)

array([ 0,  5, 10, 15])

In [7]:
np.diag(np.diag(a))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [8]:
# where

np.where(a==11)

(array([2], dtype=int64), array([3], dtype=int64))

In [9]:
loc=np.where(a==11)
type(loc)

tuple

In [34]:
print(*loc)# *:去掉dtype

[2] [3]


In [11]:
# ndarray's matrix operation

a=np.random.rand(2,2)
a=np.mat(a)
a

matrix([[ 0.75785151,  0.58777708],
        [ 0.98046399,  0.41725257]])

In [36]:
ia=np.linalg.inv(a)

[[ 1.15119376 -1.49095002]
 [-0.46747587  5.77747264]]


In [13]:
print(a*ia)# ndarray's matrix operation

a=np.random.rand(2,2)
a=np.mat(a)
a

[[  1.00000000e+00   2.22044605e-16]
 [  0.00000000e+00   1.00000000e+00]]


In [14]:
# in list or string, 'add ' concatenation, what if you really want to contenation
# using ndarray or matrix

a=np.array((1,2,3))
b=np.array((4,5,6))


In [15]:
c=np.column_stack((a,b))
c

array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
d=np.row_stack((a,b))
d

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
# for ndarray with multiple dimension
a=np.random.rand(2,2)
b=np.random.rand(2,2)
print(a)
print(b)

[[ 0.97035028  0.25041118]
 [ 0.07851449  0.19334772]]
[[ 0.77492189  0.2039282 ]
 [ 0.10193652  0.41169606]]


In [18]:
c=np.hstack([a,b])
c

array([[ 0.97035028,  0.25041118,  0.77492189,  0.2039282 ],
       [ 0.07851449,  0.19334772,  0.10193652,  0.41169606]])

In [19]:
d=np.vstack([a,b])
d

array([[ 0.97035028,  0.25041118],
       [ 0.07851449,  0.19334772],
       [ 0.77492189,  0.2039282 ],
       [ 0.10193652,  0.41169606]])

In [20]:
# look at a real example

import urllib #get data from the web

In [21]:
import os

In [22]:
if not os.path.exists('populations.txt'):# check if the file exists
    urllib.request.urlretrieve("http://www.scipy-lectures.org/_downloads/populations.txt","populations.txt")

In [23]:
! more populations.txt

3.000000000000000000e+04 4.000000000000000000e+03 4.830000000000000000e+04
4.720000000000000000e+04 6.100000000000000000e+03 4.820000000000000000e+04
7.020000000000000000e+04 9.800000000000000000e+03 4.150000000000000000e+04
7.740000000000000000e+04 3.520000000000000000e+04 3.820000000000000000e+04
3.630000000000000000e+04 5.940000000000000000e+04 4.060000000000000000e+04
2.060000000000000000e+04 4.170000000000000000e+04 3.980000000000000000e+04
1.810000000000000000e+04 1.900000000000000000e+04 3.860000000000000000e+04
2.140000000000000000e+04 1.300000000000000000e+04 4.230000000000000000e+04
2.200000000000000000e+04 8.300000000000000000e+03 4.450000000000000000e+04
2.540000000000000000e+04 9.100000000000000000e+03 4.210000000000000000e+04
2.710000000000000000e+04 7.400000000000000000e+03 4.600000000000000000e+04
4.030000000000000000e+04 8.000000000000000000e+03 4.680000000000000000e+04
5.700000000000000000e+04 1.230000000000000000e+04 4.380000000000000000e+04
7.660000000000000000e+04 

In [24]:
# #is for notation  % is a magic function, provided by jupyter notebook  ! external command sign symbol for mac, ! head -n 6 population.txt

In [25]:
# np can load tab delimited data
# automatically skip the first line if it is text

data=np.loadtxt('populations.txt',skiprows=1)
data

array([[ 47200.,   6100.,  48200.],
       [ 70200.,   9800.,  41500.],
       [ 77400.,  35200.,  38200.],
       [ 36300.,  59400.,  40600.],
       [ 20600.,  41700.,  39800.],
       [ 18100.,  19000.,  38600.],
       [ 21400.,  13000.,  42300.],
       [ 22000.,   8300.,  44500.],
       [ 25400.,   9100.,  42100.],
       [ 27100.,   7400.,  46000.],
       [ 40300.,   8000.,  46800.],
       [ 57000.,  12300.,  43800.],
       [ 76600.,  19500.,  40900.],
       [ 52300.,  45700.,  39400.],
       [ 19500.,  51100.,  39000.],
       [ 11200.,  29700.,  36700.],
       [  7600.,  15800.,  41800.],
       [ 14600.,   9700.,  43300.],
       [ 16200.,  10100.,  41300.],
       [ 24700.,   8600.,  47300.]])

In [26]:
np.savetxt('hare.txt',data[:,1])

In [27]:
! more hare.txt

6.100000000000000000e+03
9.800000000000000000e+03
3.520000000000000000e+04
5.940000000000000000e+04
4.170000000000000000e+04
1.900000000000000000e+04
1.300000000000000000e+04
8.300000000000000000e+03
9.100000000000000000e+03
7.400000000000000000e+03
8.000000000000000000e+03
1.230000000000000000e+04
1.950000000000000000e+04
4.570000000000000000e+04
5.110000000000000000e+04
2.970000000000000000e+04
1.580000000000000000e+04
9.700000000000000000e+03
1.010000000000000000e+04
8.600000000000000000e+03


In [28]:
data=np.loadtxt('populations.txt').astype('int')
data

array([[30000,  4000, 48300],
       [47200,  6100, 48200],
       [70200,  9800, 41500],
       [77400, 35200, 38200],
       [36300, 59400, 40600],
       [20600, 41700, 39800],
       [18100, 19000, 38600],
       [21400, 13000, 42300],
       [22000,  8300, 44500],
       [25400,  9100, 42100],
       [27100,  7400, 46000],
       [40300,  8000, 46800],
       [57000, 12300, 43800],
       [76600, 19500, 40900],
       [52300, 45700, 39400],
       [19500, 51100, 39000],
       [11200, 29700, 36700],
       [ 7600, 15800, 41800],
       [14600,  9700, 43300],
       [16200, 10100, 41300],
       [24700,  8600, 47300]])

In [29]:
# the mean of the populations for each species
data.mean(axis=0).astype('int')

array([34080, 20166, 42400])

In [30]:
# which year each species had the largest population
data.max(axis=0)

array([77400, 59400, 48300])

In [31]:
populations=data[:,1:]
populations

array([[ 4000, 48300],
       [ 6100, 48200],
       [ 9800, 41500],
       [35200, 38200],
       [59400, 40600],
       [41700, 39800],
       [19000, 38600],
       [13000, 42300],
       [ 8300, 44500],
       [ 9100, 42100],
       [ 7400, 46000],
       [ 8000, 46800],
       [12300, 43800],
       [19500, 40900],
       [45700, 39400],
       [51100, 39000],
       [29700, 36700],
       [15800, 41800],
       [ 9700, 43300],
       [10100, 41300],
       [ 8600, 47300]])

In [32]:
year,hare,lynx,carrot=data.T

ValueError: not enough values to unpack (expected 4, got 3)

In [ ]:
year

In [ ]:
hare

In [ ]:
lynx

In [ ]:
carrot

In [ ]:
np.argmax(data,axis=0)

In [ ]:
year[np.argmax(populations,axis=0)] # the location of the largest element

In [ ]:
# which year hare is above 50000
year[hare>50000]

In [ ]:
# which years any of the populations is above 50000

In [ ]:
year[np.any(populations>50000,axis=1)]

In [ ]:
# panda is python package for data analysis
# the name has nothing to do with panda bear,but derived from the term "panel data"

# Essential concepts:
# a dictionary is a key-value pair
# "breakfast":"ham"

# A series is a named python list(dict with list as value)
# 'grades':[50,90,100,45]

# A data frame is a dictionary of Series(dict of series)
#