In [1]:
import numpy as np

In [2]:
a=np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [3]:
np.tril(a)

array([[ 0,  0,  0,  0,  0],
       [ 5,  6,  0,  0,  0],
       [10, 11, 12,  0,  0],
       [15, 16, 17, 18,  0],
       [20, 21, 22, 23, 24]])

In [4]:
np.tril(a,-1)

array([[ 0,  0,  0,  0,  0],
       [ 5,  0,  0,  0,  0],
       [10, 11,  0,  0,  0],
       [15, 16, 17,  0,  0],
       [20, 21, 22, 23,  0]])

In [5]:
np.triu(a)

array([[ 0,  1,  2,  3,  4],
       [ 0,  6,  7,  8,  9],
       [ 0,  0, 12, 13, 14],
       [ 0,  0,  0, 18, 19],
       [ 0,  0,  0,  0, 24]])

In [6]:
np.triu(a,-1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 0, 11, 12, 13, 14],
       [ 0,  0, 17, 18, 19],
       [ 0,  0,  0, 23, 24]])

In [7]:
np.diag(a)

array([ 0,  6, 12, 18, 24])

In [9]:
np.diag(np.diag(a))

array([[ 0,  0,  0,  0,  0],
       [ 0,  6,  0,  0,  0],
       [ 0,  0, 12,  0,  0],
       [ 0,  0,  0, 18,  0],
       [ 0,  0,  0,  0, 24]])

In [10]:
np.where(a==11)

(array([2], dtype=int64), array([1], dtype=int64))

In [11]:
loc=np.where(a==11)
print(loc)

(array([2], dtype=int64), array([1], dtype=int64))


In [12]:
print(*loc)

[2] [1]


In [14]:
mac=np.where(a==12)
print(*mac)

[2] [2]


In [15]:
type(loc)

tuple

In [16]:
a=np.random.rand(2,2)
a=np.mat(a)
a

matrix([[ 0.63288795,  0.09241115],
        [ 0.58062914,  0.06457545]])

In [17]:
ia=np.linalg.inv(a)
ia

matrix([[ -5.04985561,   7.22663138],
        [ 45.40569871, -49.49238268]])

In [20]:
print(a*ia)

[[  1.00000000e+00   0.00000000e+00]
 [ -4.44089210e-16   1.00000000e+00]]


In [23]:
a=np.array((1,2,3))
b=np.array((4,5,6))
c=np.column_stack((a,b))
c

array([[1, 4],
       [2, 5],
       [3, 6]])

In [24]:
d=np.row_stack((a,b))
d

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
a=np.random.rand(2,2)
b=np.random.rand(2,2)
c=np.hstack((a,b))
c

array([[ 0.21154258,  0.20514026,  0.89063771,  0.17918092],
       [ 0.37222813,  0.0966334 ,  0.38371841,  0.6502271 ]])

In [27]:
d=np.vstack((a,b))
d

array([[ 0.21154258,  0.20514026],
       [ 0.37222813,  0.0966334 ],
       [ 0.89063771,  0.17918092],
       [ 0.38371841,  0.6502271 ]])

In [28]:
a

array([[ 0.21154258,  0.20514026],
       [ 0.37222813,  0.0966334 ]])

In [29]:
b

array([[ 0.89063771,  0.17918092],
       [ 0.38371841,  0.6502271 ]])

In [30]:
import urllib

In [31]:
import os

In [33]:
if not os.path.exists('population.txt'):
    urllib.request.urlretrieve("http://www.scipy-lectures.org/_downloads/populations.txt"),("populations.txt")

In [34]:
! more populations.txt

# year  hare    lynx    carrot
1900    30e3    4e3     48300
1901    47.2e3  6.1e3   48200
1902    70.2e3  9.8e3   41500
1903    77.4e3  35.2e3  38200
1904    36.3e3  59.4e3  40600
1905    20.6e3  41.7e3  39800
1906    18.1e3  19e3    38600
1907    21.4e3  13e3    42300
1908    22e3    8.3e3   44500
1909    25.4e3  9.1e3   42100
1910    27.1e3  7.4e3   46000
1911    40.3e3  8e3     46800
1912    57e3    12.3e3  43800
1913    76.6e3  19.5e3  40900
1914    52.3e3  45.7e3  39400
1915    19.5e3  51.1e3  39000
1916    11.2e3  29.7e3  36700
1917    7.6e3   15.8e3  41800
1918    14.6e3  9.7e3   43300
1919    16.2e3  10.1e3  41300
1920    24.7e3  8.6e3   47300


In [38]:
urllib.request.urlretrieve("http://www.scipy-lectures.org/_downloads/populations.txt"),("population.txt")

(('C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\tmpamq9o8sm',
  <http.client.HTTPMessage at 0x1e4f5b0ffd0>),
 'population.txt')

In [39]:
! more population.txt

无法访问 C:\Users\Administrator\Dropbox\Media data analytics\jupyter notebook\population.txt 文件


In [43]:
if not os.path.exists('populations.txt'):
    urllib.request.urlretrieve("http://www.scipy-lectures.org/_downloads/populations.txt"),("populations.txt")

In [45]:
! more populations.txt

# year  hare    lynx    carrot
1900    30e3    4e3     48300
1901    47.2e3  6.1e3   48200
1902    70.2e3  9.8e3   41500
1903    77.4e3  35.2e3  38200
1904    36.3e3  59.4e3  40600
1905    20.6e3  41.7e3  39800
1906    18.1e3  19e3    38600
1907    21.4e3  13e3    42300
1908    22e3    8.3e3   44500
1909    25.4e3  9.1e3   42100
1910    27.1e3  7.4e3   46000
1911    40.3e3  8e3     46800
1912    57e3    12.3e3  43800
1913    76.6e3  19.5e3  40900
1914    52.3e3  45.7e3  39400
1915    19.5e3  51.1e3  39000
1916    11.2e3  29.7e3  36700
1917    7.6e3   15.8e3  41800
1918    14.6e3  9.7e3   43300
1919    16.2e3  10.1e3  41300
1920    24.7e3  8.6e3   47300


In [46]:
data=np.loadtxt('populations.txt',skiprows=0)
data

array([[  1900.,  30000.,   4000.,  48300.],
       [  1901.,  47200.,   6100.,  48200.],
       [  1902.,  70200.,   9800.,  41500.],
       [  1903.,  77400.,  35200.,  38200.],
       [  1904.,  36300.,  59400.,  40600.],
       [  1905.,  20600.,  41700.,  39800.],
       [  1906.,  18100.,  19000.,  38600.],
       [  1907.,  21400.,  13000.,  42300.],
       [  1908.,  22000.,   8300.,  44500.],
       [  1909.,  25400.,   9100.,  42100.],
       [  1910.,  27100.,   7400.,  46000.],
       [  1911.,  40300.,   8000.,  46800.],
       [  1912.,  57000.,  12300.,  43800.],
       [  1913.,  76600.,  19500.,  40900.],
       [  1914.,  52300.,  45700.,  39400.],
       [  1915.,  19500.,  51100.,  39000.],
       [  1916.,  11200.,  29700.,  36700.],
       [  1917.,   7600.,  15800.,  41800.],
       [  1918.,  14600.,   9700.,  43300.],
       [  1919.,  16200.,  10100.,  41300.],
       [  1920.,  24700.,   8600.,  47300.]])

In [47]:
data=np.loadtxt('populations.txt',skiprows=1)
data

array([[  1900.,  30000.,   4000.,  48300.],
       [  1901.,  47200.,   6100.,  48200.],
       [  1902.,  70200.,   9800.,  41500.],
       [  1903.,  77400.,  35200.,  38200.],
       [  1904.,  36300.,  59400.,  40600.],
       [  1905.,  20600.,  41700.,  39800.],
       [  1906.,  18100.,  19000.,  38600.],
       [  1907.,  21400.,  13000.,  42300.],
       [  1908.,  22000.,   8300.,  44500.],
       [  1909.,  25400.,   9100.,  42100.],
       [  1910.,  27100.,   7400.,  46000.],
       [  1911.,  40300.,   8000.,  46800.],
       [  1912.,  57000.,  12300.,  43800.],
       [  1913.,  76600.,  19500.,  40900.],
       [  1914.,  52300.,  45700.,  39400.],
       [  1915.,  19500.,  51100.,  39000.],
       [  1916.,  11200.,  29700.,  36700.],
       [  1917.,   7600.,  15800.,  41800.],
       [  1918.,  14600.,   9700.,  43300.],
       [  1919.,  16200.,  10100.,  41300.],
       [  1920.,  24700.,   8600.,  47300.]])

In [48]:
data=np.loadtxt('populations.txt',skiprows=2)
data

array([[  1901.,  47200.,   6100.,  48200.],
       [  1902.,  70200.,   9800.,  41500.],
       [  1903.,  77400.,  35200.,  38200.],
       [  1904.,  36300.,  59400.,  40600.],
       [  1905.,  20600.,  41700.,  39800.],
       [  1906.,  18100.,  19000.,  38600.],
       [  1907.,  21400.,  13000.,  42300.],
       [  1908.,  22000.,   8300.,  44500.],
       [  1909.,  25400.,   9100.,  42100.],
       [  1910.,  27100.,   7400.,  46000.],
       [  1911.,  40300.,   8000.,  46800.],
       [  1912.,  57000.,  12300.,  43800.],
       [  1913.,  76600.,  19500.,  40900.],
       [  1914.,  52300.,  45700.,  39400.],
       [  1915.,  19500.,  51100.,  39000.],
       [  1916.,  11200.,  29700.,  36700.],
       [  1917.,   7600.,  15800.,  41800.],
       [  1918.,  14600.,   9700.,  43300.],
       [  1919.,  16200.,  10100.,  41300.],
       [  1920.,  24700.,   8600.,  47300.]])

In [49]:
np.savetxt('hare.txt',data[:,1])

In [50]:
! more hare.txt

4.720000000000000000e+04
7.020000000000000000e+04
7.740000000000000000e+04
3.630000000000000000e+04
2.060000000000000000e+04
1.810000000000000000e+04
2.140000000000000000e+04
2.200000000000000000e+04
2.540000000000000000e+04
2.710000000000000000e+04
4.030000000000000000e+04
5.700000000000000000e+04
7.660000000000000000e+04
5.230000000000000000e+04
1.950000000000000000e+04
1.120000000000000000e+04
7.600000000000000000e+03
1.460000000000000000e+04
1.620000000000000000e+04
2.470000000000000000e+04


In [51]:
data=np.loadtxt('populations.txt').astype('int')
data

array([[ 1900, 30000,  4000, 48300],
       [ 1901, 47200,  6100, 48200],
       [ 1902, 70200,  9800, 41500],
       [ 1903, 77400, 35200, 38200],
       [ 1904, 36300, 59400, 40600],
       [ 1905, 20600, 41700, 39800],
       [ 1906, 18100, 19000, 38600],
       [ 1907, 21400, 13000, 42300],
       [ 1908, 22000,  8300, 44500],
       [ 1909, 25400,  9100, 42100],
       [ 1910, 27100,  7400, 46000],
       [ 1911, 40300,  8000, 46800],
       [ 1912, 57000, 12300, 43800],
       [ 1913, 76600, 19500, 40900],
       [ 1914, 52300, 45700, 39400],
       [ 1915, 19500, 51100, 39000],
       [ 1916, 11200, 29700, 36700],
       [ 1917,  7600, 15800, 41800],
       [ 1918, 14600,  9700, 43300],
       [ 1919, 16200, 10100, 41300],
       [ 1920, 24700,  8600, 47300]])

In [55]:
data.mean(axis=0).astype('int')

array([ 1910, 34080, 20166, 42400])

In [56]:
data.max(axis=0).astype('int')

array([ 1920, 77400, 59400, 48300])

In [57]:
populations=data[:,1:]
populations

array([[30000,  4000, 48300],
       [47200,  6100, 48200],
       [70200,  9800, 41500],
       [77400, 35200, 38200],
       [36300, 59400, 40600],
       [20600, 41700, 39800],
       [18100, 19000, 38600],
       [21400, 13000, 42300],
       [22000,  8300, 44500],
       [25400,  9100, 42100],
       [27100,  7400, 46000],
       [40300,  8000, 46800],
       [57000, 12300, 43800],
       [76600, 19500, 40900],
       [52300, 45700, 39400],
       [19500, 51100, 39000],
       [11200, 29700, 36700],
       [ 7600, 15800, 41800],
       [14600,  9700, 43300],
       [16200, 10100, 41300],
       [24700,  8600, 47300]])

In [58]:
np.savetxt('populations.txt',data[:,1:])

In [59]:
! more populations.txt

3.000000000000000000e+04 4.000000000000000000e+03 4.830000000000000000e+04
4.720000000000000000e+04 6.100000000000000000e+03 4.820000000000000000e+04
7.020000000000000000e+04 9.800000000000000000e+03 4.150000000000000000e+04
7.740000000000000000e+04 3.520000000000000000e+04 3.820000000000000000e+04
3.630000000000000000e+04 5.940000000000000000e+04 4.060000000000000000e+04
2.060000000000000000e+04 4.170000000000000000e+04 3.980000000000000000e+04
1.810000000000000000e+04 1.900000000000000000e+04 3.860000000000000000e+04
2.140000000000000000e+04 1.300000000000000000e+04 4.230000000000000000e+04
2.200000000000000000e+04 8.300000000000000000e+03 4.450000000000000000e+04
2.540000000000000000e+04 9.100000000000000000e+03 4.210000000000000000e+04
2.710000000000000000e+04 7.400000000000000000e+03 4.600000000000000000e+04
4.030000000000000000e+04 8.000000000000000000e+03 4.680000000000000000e+04
5.700000000000000000e+04 1.230000000000000000e+04 4.380000000000000000e+04
7.660000000000000000e+04 

In [60]:
year,hare,lynx,carrot=data.T

In [61]:
year

array([1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910,
       1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920])

In [62]:
np.argmax(data,axis=0)

array([20,  3,  4,  0], dtype=int64)

In [65]:
year[np.argmax(data,axis=0)]

array([1920, 1903, 1904, 1900])

In [66]:
year[hare>40000]

array([1901, 1902, 1903, 1911, 1912, 1913, 1914])

In [70]:
year[np.any(populations>5000,axis=1)]

array([1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910,
       1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920])

In [71]:
year[np.any(populations>5000)]

array([[1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910,
        1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920]])

In [73]:
import pandas as pd

In [74]:
import numpy as np

In [75]:
from pandas import Series, DataFrame

In [77]:
a=np.random.rand(5)
a

array([ 0.96045547,  0.2593673 ,  0.64643588,  0.98699508,  0.78794969])

In [79]:
s=Series(a)
s

0    0.960455
1    0.259367
2    0.646436
3    0.986995
4    0.787950
dtype: float64

In [80]:
s=Series(np.random.rand(5),index=['a','b','c','d','e'])
s

a    0.627337
b    0.931358
c    0.162133
d    0.669119
e    0.945303
dtype: float64

In [81]:
s.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [82]:
s.values

array([ 0.62733693,  0.93135816,  0.16213305,  0.66911869,  0.9453034 ])

In [83]:
s=Series(np.random.rand(5),index=['a','b','c','d','e'],name='my series')
s

a    0.995915
b    0.667462
c    0.161438
d    0.314497
e    0.588242
Name: my series, dtype: float64

In [84]:
d={'a':0,'b':1,'c':2}
print(d)

{'a': 0, 'b': 1, 'c': 2}


In [86]:
s=Series(d,index=['c','b','d'])
s

c    2.0
b    1.0
d    NaN
dtype: float64

In [88]:
s=Series(100,index=['a','b','c','d','e'])
s

a    100
b    100
c    100
d    100
e    100
dtype: int64

In [89]:
s=Series([100,200,300,400,500],index=['a','b','c','d','e'])
s

a    100
b    200
c    300
d    400
e    500
dtype: int64

In [90]:
s=Series(np.random.rand(5),index=['a','b','c','d','e'])
s

a    0.810396
b    0.179873
c    0.524020
d    0.207219
e    0.758489
dtype: float64

In [91]:
s[0]

0.81039563738093878

In [92]:
s[:2]

a    0.810396
b    0.179873
dtype: float64

In [93]:
s[:1]

a    0.810396
dtype: float64

In [94]:
s[[0]]

a    0.810396
dtype: float64

In [95]:
s[[0,2,4]]

a    0.810396
c    0.524020
e    0.758489
dtype: float64

In [96]:
s[['e','a']]

e    0.758489
a    0.810396
dtype: float64

In [97]:
s[s>0.5]

a    0.810396
c    0.524020
e    0.758489
dtype: float64

In [99]:
'd' in s

True

In [102]:
x={'Serena':Series([163,50,22],index=['Height','Weight','BMI']),'Lucas':Series([101,15,25],index=['Height','Weight','BMI'])}
fam=DataFrame(x)
fam

Lucas  Serena
Height    101     163
Weight     15      50
BMI        25      22

In [105]:
fam2=DataFrame(fam,['Height','Weight','Shoulder'],columns=['Lucas','Serena','Ian'])
fam2

Lucas  Serena  Ian
Height    101.0   163.0  NaN
Weight     15.0    50.0  NaN
Shoulder    NaN     NaN  NaN

In [107]:
fam2.index

Index(['Height', 'Weight', 'Shoulder'], dtype='object')

In [108]:
fam2.columns

Index(['Lucas', 'Serena', 'Ian'], dtype='object')

In [109]:
fam2.values

array([[ 101.,  163.,   nan],
       [  15.,   50.,   nan],
       [  nan,   nan,   nan]])

In [110]:
a=Series([163,180,101])
b=Series([50,77,15])
fam=pd.concat([a,b],axis=1)
fam

0   1
0  163  50
1  180  77
2  101  15

In [119]:
fam=DataFrame()
index=['Height','Weight','Shoulders']
for i in range(3):
    a=DataFrame([np.linspace(i,3*i,3)],index=[index[i]],columns=['Serena','Ian','Lucas'])
    fam=pd.concat([a,fam],axis=0)
fam

Serena  Ian  Lucas
Shoulders     2.0  4.0    6.0
Weight        1.0  2.0    3.0
Height        0.0  0.0    0.0

In [121]:
fam['Serena']

Shoulders    2.0
Weight       1.0
Height       0.0
Name: Serena, dtype: float64

In [122]:
fam.columns

Index(['Serena', 'Ian', 'Lucas'], dtype='object')

In [124]:
fam.columns=['Ian','Serena','Lucas']
fam

Ian  Serena  Lucas
Shoulders  2.0     4.0    6.0
Weight     1.0     2.0    3.0
Height     0.0     0.0    0.0

In [126]:
fam[['Serena','Lucas']]

Serena  Lucas
Shoulders     4.0    6.0
Weight        2.0    3.0
Height        0.0    0.0

In [128]:
fam.Serena

Shoulders    4.0
Weight       2.0
Height       0.0
Name: Serena, dtype: float64

In [130]:
fam['Serena']['Height']

0.0

In [132]:
fam['Serena'][1]

2.0

In [136]:
fam.iloc[1]

Ian       1.0
Serena    2.0
Lucas     3.0
Name: Weight, dtype: float64

In [141]:
fam[1:3]

Ian  Serena  Lucas
Weight  1.0     2.0    3.0
Height  0.0     0.0    0.0

In [145]:
bv=[False, False, True]
fam[bv]

Ian  Serena  Lucas
Height  0.0     0.0    0.0

In [150]:
fam[['Ian','Serena']].iloc[[1,2]]

Ian  Serena
Weight  1.0     2.0
Height  0.0     0.0

In [158]:
print(fam)
fam.iat[1,2]

           Ian  Serena  Lucas
Shoulders  2.0     4.0    6.0
Weight     1.0     2.0    3.0
Height     0.0     0.0    0.0


3.0

In [159]:
fam.at['Weight','Serena']

2.0

In [157]:
fam.ix['Weight',0]

C:\Users\Administrator\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


1.0

In [165]:
fam.ix[['Weight','Height'],[0,2]]

Ian  Lucas
Weight  1.0    3.0
Height  0.0    0.0

In [168]:
fam.ix[[1,'Height'],[1,'Lucas']]

1  Lucas
1      NaN    NaN
Height NaN    0.0

In [172]:
dates=pd.date_range('20170101',freq='M',periods=6)
dates

DatetimeIndex(['2017-01-31', '2017-02-28', '2017-03-31', '2017-04-30',
               '2017-05-31', '2017-06-30'],
              dtype='datetime64[ns]', freq='M')

In [175]:
dates=pd.date_range('20170101',freq='A',periods=2)
dates

DatetimeIndex(['2017-12-31', '2018-12-31'], dtype='datetime64[ns]', freq='A-DEC')

In [177]:
dates=pd.date_range(start='20150101',end='20150107')
dates

DatetimeIndex(['2015-01-01', '2015-01-02', '2015-01-03', '2015-01-04',
               '2015-01-05', '2015-01-06', '2015-01-07'],
              dtype='datetime64[ns]', freq='D')

In [180]:
df=pd.DataFrame(np.random.rand(7,7),index=dates,columns=list('ABCDEFG'))
df

A         B         C         D         E         F  \
2015-01-01  0.416320  0.097253  0.751964  0.152854  0.671645  0.017727   
2015-01-02  0.184298  0.786021  0.608242  0.972175  0.300115  0.404478   
2015-01-03  0.624478  0.342559  0.866948  0.426475  0.300125  0.870027   
2015-01-04  0.294050  0.413746  0.465717  0.770863  0.350963  0.851872   
2015-01-05  0.423223  0.324313  0.494108  0.934407  0.879381  0.864867   
2015-01-06  0.872500  0.244615  0.176887  0.944612  0.556042  0.635026   
2015-01-07  0.561765  0.578319  0.776931  0.498959  0.294968  0.292885   

                   G  
2015-01-01  0.253576  
2015-01-02  0.559179  
2015-01-03  0.654730  
2015-01-04  0.634365  
2015-01-05  0.020720  
2015-01-06  0.089163  
2015-01-07  0.202227

In [182]:
! pip install pandas-datareader

In [183]:
from pandas_datareader import data

In [185]:
import datetime

In [187]:
start=datetime.datetime(2017,1,1)
end=datetime.datetime(2017,1,21)

In [189]:
df=data.DataReader('AAPL','quandl',start,end)
df

Open      High       Low   Close      Volume  ExDividend  \
Date                                                                      
2017-01-20  120.450  120.4500  119.7346  120.00  32597892.0         0.0   
2017-01-19  119.400  120.0900  119.3700  119.78  25597291.0         0.0   
2017-01-18  120.000  120.5000  119.7100  119.99  23712961.0         0.0   
2017-01-17  118.340  120.2400  118.2200  120.00  34439843.0         0.0   
2017-01-13  119.110  119.6200  118.8100  119.04  26111948.0         0.0   
2017-01-12  118.895  119.3000  118.2100  119.25  27086220.0         0.0   
2017-01-11  118.740  119.9300  118.6000  119.75  27588593.0         0.0   
2017-01-10  118.770  119.3800  118.3000  119.11  24462051.0         0.0   
2017-01-09  117.950  119.4300  117.9400  118.99  33561948.0         0.0   
2017-01-06  116.780  118.1600  116.4700  117.91  31751900.0         0.0   
2017-01-05  115.920  116.8642  115.8100  116.61  22193587.0         0.0   
2017-01-04  115.850  116.5100  115.7500  116.02  21118116.0         0.0   
2017-01-03  115.800  116.3300  114.7600  116.15  28781865.0         0.0   

            SplitRatio     AdjOpen     AdjHigh      AdjLow    AdjClose  \
Date                                                                     
2017-01-20         1.0  118.962267  118.962267  118.255703  118.517825   
2017-01-19         1.0  117.925236  118.606713  117.895606  118.300542   
2017-01-18         1.0  118.517825  119.011649  118.231407  118.507948   
2017-01-17         1.0  116.878328  118.754860  116.759810  118.517825   
2017-01-13         1.0  117.638817  118.142518  117.342523  117.569682   
2017-01-12         1.0  117.426473  117.826471  116.749934  117.777088   
2017-01-11         1.0  117.273388  118.448689  117.135117  118.270913   
2017-01-10         1.0  117.303017  117.905483  116.838822  117.638817   
2017-01-09         1.0  116.493145  117.954865  116.483269  117.520300   
2017-01-06         1.0  115.337596  116.700551  115.031425  116.453639   
2017-01-05         1.0  114.488219  115.420756  114.379577  115.169696   
2017-01-04         1.0  114.419083  115.070931  114.320318  114.586983   
2017-01-03         1.0  114.369701  114.893155  113.342546  114.715378   

             AdjVolume  
Date                    
2017-01-20  32597892.0  
2017-01-19  25597291.0  
2017-01-18  23712961.0  
2017-01-17  34439843.0  
2017-01-13  26111948.0  
2017-01-12  27086220.0  
2017-01-11  27588593.0  
2017-01-10  24462051.0  
2017-01-09  33561948.0  
2017-01-06  31751900.0  
2017-01-05  22193587.0  
2017-01-04  21118116.0  
2017-01-03  28781865.0

In [191]:
type(df)

pandas.core.frame.DataFrame

In [193]:
df.shape

(13, 12)

In [195]:
df.head(3)

Open    High       Low   Close      Volume  ExDividend  \
Date                                                                   
2017-01-20  120.45  120.45  119.7346  120.00  32597892.0         0.0   
2017-01-19  119.40  120.09  119.3700  119.78  25597291.0         0.0   
2017-01-18  120.00  120.50  119.7100  119.99  23712961.0         0.0   

            SplitRatio     AdjOpen     AdjHigh      AdjLow    AdjClose  \
Date                                                                     
2017-01-20         1.0  118.962267  118.962267  118.255703  118.517825   
2017-01-19         1.0  117.925236  118.606713  117.895606  118.300542   
2017-01-18         1.0  118.517825  119.011649  118.231407  118.507948   

             AdjVolume  
Date                    
2017-01-20  32597892.0  
2017-01-19  25597291.0  
2017-01-18  23712961.0

In [197]:
df.tail(3)

Open      High     Low   Close      Volume  ExDividend  \
Date                                                                   
2017-01-05  115.92  116.8642  115.81  116.61  22193587.0         0.0   
2017-01-04  115.85  116.5100  115.75  116.02  21118116.0         0.0   
2017-01-03  115.80  116.3300  114.76  116.15  28781865.0         0.0   

            SplitRatio     AdjOpen     AdjHigh      AdjLow    AdjClose  \
Date                                                                     
2017-01-05         1.0  114.488219  115.420756  114.379577  115.169696   
2017-01-04         1.0  114.419083  115.070931  114.320318  114.586983   
2017-01-03         1.0  114.369701  114.893155  113.342546  114.715378   

             AdjVolume  
Date                    
2017-01-05  22193587.0  
2017-01-04  21118116.0  
2017-01-03  28781865.0

In [199]:
df.describe()

Open        High         Low       Close        Volume  \
count   13.000000   13.000000   13.000000   13.000000  1.300000e+01   
mean   118.154231  118.984938  117.821892  118.661538  2.761571e+07   
std      1.586986    1.509417    1.614950    1.489999  4.364900e+06   
min    115.800000  116.330000  114.760000  116.020000  2.111812e+07   
25%    116.780000  118.160000  116.470000  117.910000  2.446205e+07   
50%    118.740000  119.430000  118.220000  119.110000  2.708622e+07   
75%    119.110000  120.090000  118.810000  119.780000  3.175190e+07   
max    120.450000  120.500000  119.734600  120.000000  3.443984e+07   

       ExDividend  SplitRatio     AdjOpen     AdjHigh      AdjLow    AdjClose  \
count        13.0        13.0   13.000000   13.000000   13.000000   13.000000   
mean          0.0         1.0  116.694853  117.515301  116.366620  117.195895   
std           0.0         0.0    1.567384    1.490774    1.595003    1.471595   
min           0.0         1.0  114.369701  114.893155  113.342546  114.586983   
25%           0.0         1.0  115.337596  116.700551  115.031425  116.453639   
50%           0.0         1.0  117.273388  117.954865  116.759810  117.638817   
75%           0.0         1.0  117.638817  118.606713  117.342523  118.300542   
max           0.0         1.0  118.962267  119.011649  118.255703  118.517825   

          AdjVolume  
count  1.300000e+01  
mean   2.761571e+07  
std    4.364900e+06  
min    2.111812e+07  
25%    2.446205e+07  
50%    2.708622e+07  
75%    3.175190e+07  
max    3.443984e+07

In [204]:
df.sort_index(axis=1,ascending=True).head(3)

AdjClose     AdjHigh      AdjLow     AdjOpen   AdjVolume  \
Date                                                                     
2017-01-20  118.517825  118.962267  118.255703  118.962267  32597892.0   
2017-01-19  118.300542  118.606713  117.895606  117.925236  25597291.0   
2017-01-18  118.507948  119.011649  118.231407  118.517825  23712961.0   

             Close  ExDividend    High       Low    Open  SplitRatio  \
Date                                                                   
2017-01-20  120.00         0.0  120.45  119.7346  120.45         1.0   
2017-01-19  119.78         0.0  120.09  119.3700  119.40         1.0   
2017-01-18  119.99         0.0  120.50  119.7100  120.00         1.0   

                Volume  
Date                    
2017-01-20  32597892.0  
2017-01-19  25597291.0  
2017-01-18  23712961.0

In [207]:
df.sort_values(by='AdjClose',axis=0,ascending=True).head(4)

Open      High     Low   Close      Volume  ExDividend  \
Date                                                                   
2017-01-04  115.85  116.5100  115.75  116.02  21118116.0         0.0   
2017-01-03  115.80  116.3300  114.76  116.15  28781865.0         0.0   
2017-01-05  115.92  116.8642  115.81  116.61  22193587.0         0.0   
2017-01-06  116.78  118.1600  116.47  117.91  31751900.0         0.0   

            SplitRatio     AdjOpen     AdjHigh      AdjLow    AdjClose  \
Date                                                                     
2017-01-04         1.0  114.419083  115.070931  114.320318  114.586983   
2017-01-03         1.0  114.369701  114.893155  113.342546  114.715378   
2017-01-05         1.0  114.488219  115.420756  114.379577  115.169696   
2017-01-06         1.0  115.337596  116.700551  115.031425  116.453639   

             AdjVolume  
Date                    
2017-01-04  21118116.0  
2017-01-03  28781865.0  
2017-01-05  22193587.0  
2017-01-06  31751900.0

In [208]:
df.sort_values(by=['Volume','AdjClose'],ascending=[False,True]).head()

Open    High       Low   Close      Volume  ExDividend  \
Date                                                                   
2017-01-17  118.34  120.24  118.2200  120.00  34439843.0         0.0   
2017-01-09  117.95  119.43  117.9400  118.99  33561948.0         0.0   
2017-01-20  120.45  120.45  119.7346  120.00  32597892.0         0.0   
2017-01-06  116.78  118.16  116.4700  117.91  31751900.0         0.0   
2017-01-03  115.80  116.33  114.7600  116.15  28781865.0         0.0   

            SplitRatio     AdjOpen     AdjHigh      AdjLow    AdjClose  \
Date                                                                     
2017-01-17         1.0  116.878328  118.754860  116.759810  118.517825   
2017-01-09         1.0  116.493145  117.954865  116.483269  117.520300   
2017-01-20         1.0  118.962267  118.962267  118.255703  118.517825   
2017-01-06         1.0  115.337596  116.700551  115.031425  116.453639   
2017-01-03         1.0  114.369701  114.893155  113.342546  114.715378   

             AdjVolume  
Date                    
2017-01-17  34439843.0  
2017-01-09  33561948.0  
2017-01-20  32597892.0  
2017-01-06  31751900.0  
2017-01-03  28781865.0

In [220]:
df.iloc[1:4][1:4][1:1]

Empty DataFrame
Columns: [Open, High, Low, Close, Volume, ExDividend, SplitRatio, AdjOpen, AdjHigh, AdjLow, AdjClose, AdjVolume]
Index: []

In [223]:
df[df.Open>df.Open.mean()]

Open    High       Low   Close      Volume  ExDividend  \
Date                                                                    
2017-01-20  120.450  120.45  119.7346  120.00  32597892.0         0.0   
2017-01-19  119.400  120.09  119.3700  119.78  25597291.0         0.0   
2017-01-18  120.000  120.50  119.7100  119.99  23712961.0         0.0   
2017-01-17  118.340  120.24  118.2200  120.00  34439843.0         0.0   
2017-01-13  119.110  119.62  118.8100  119.04  26111948.0         0.0   
2017-01-12  118.895  119.30  118.2100  119.25  27086220.0         0.0   
2017-01-11  118.740  119.93  118.6000  119.75  27588593.0         0.0   
2017-01-10  118.770  119.38  118.3000  119.11  24462051.0         0.0   

            SplitRatio     AdjOpen     AdjHigh      AdjLow    AdjClose  \
Date                                                                     
2017-01-20         1.0  118.962267  118.962267  118.255703  118.517825   
2017-01-19         1.0  117.925236  118.606713  117.895606  118.300542   
2017-01-18         1.0  118.517825  119.011649  118.231407  118.507948   
2017-01-17         1.0  116.878328  118.754860  116.759810  118.517825   
2017-01-13         1.0  117.638817  118.142518  117.342523  117.569682   
2017-01-12         1.0  117.426473  117.826471  116.749934  117.777088   
2017-01-11         1.0  117.273388  118.448689  117.135117  118.270913   
2017-01-10         1.0  117.303017  117.905483  116.838822  117.638817   

             AdjVolume  
Date                    
2017-01-20  32597892.0  
2017-01-19  25597291.0  
2017-01-18  23712961.0  
2017-01-17  34439843.0  
2017-01-13  26111948.0  
2017-01-12  27086220.0  
2017-01-11  27588593.0  
2017-01-10  24462051.0